using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LingualLoop.Api.Migrations;

public partial class AddUserLeagueProgress : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS user_league_progress (
                user_league_progress_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id text NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
                season_key integer NOT NULL,
                points integer NOT NULL DEFAULT 0,
                updated_at timestamp with time zone NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ix_user_league_progress_user_id_season_key
                ON user_league_progress (user_id, season_key);

            CREATE INDEX IF NOT EXISTS ix_user_league_progress_season_key_points
                ON user_league_progress (season_key, points DESC);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "user_league_progress");
    }
}
