using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LingualLoop.Api.Migrations;

public partial class AddUserDailyActivityAndStreak : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS user_daily_activity (
                user_daily_activity_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id text NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
                activity_date date NOT NULL,
                created_at timestamp with time zone NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ix_user_daily_activity_user_id_activity_date
                ON user_daily_activity (user_id, activity_date);

            CREATE TABLE IF NOT EXISTS user_streak (
                user_streak_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id text NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
                current_streak integer NOT NULL,
                longest_streak integer NOT NULL,
                last_active_date date NOT NULL,
                updated_at timestamp with time zone NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ix_user_streak_user_id
                ON user_streak (user_id);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "user_daily_activity");
        migrationBuilder.DropTable(name: "user_streak");
    }
}
