using Microsoft.EntityFrameworkCore;
using Postgres;

namespace Service.Helpers;

public static class KartyLearningSchemaHelper
{
    private static readonly SemaphoreSlim SchemaLock = new(1, 1);
    private static bool _isReady;

    public static async Task EnsureCreatedAsync(
        LingualLoopContext context,
        CancellationToken cancellationToken)
    {
        if (_isReady) return;

        await SchemaLock.WaitAsync(cancellationToken);
        try
        {
            if (_isReady) return;
            await context.Database.ExecuteSqlRawAsync(
                """
            ALTER TABLE karty ADD COLUMN IF NOT EXISTS noun_text text;
            ALTER TABLE karty ADD COLUMN IF NOT EXISTS article text;

            UPDATE karty
            SET article = lower(split_part(trim(
                    CASE
                        WHEN nullif(trim(correct_text), '') IS NOT NULL THEN correct_text
                        ELSE question_text
                    END
                ), ' ', 1)),
                noun_text = regexp_replace(trim(
                    CASE
                        WHEN nullif(trim(correct_text), '') IS NOT NULL THEN correct_text
                        ELSE question_text
                    END
                ), '^(der|die|das)\s+', '', 'i')
            WHERE nullif(trim(noun_text), '') IS NULL
               OR nullif(trim(article), '') IS NULL;

            ALTER TABLE karty ALTER COLUMN noun_text SET NOT NULL;
            ALTER TABLE karty ALTER COLUMN article SET NOT NULL;

            CREATE TABLE IF NOT EXISTS user_karty_learning
            (
                user_karty_learning_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id text NOT NULL,
                karty_id integer NOT NULL,
                correct_count integer NOT NULL DEFAULT 1,
                article_attempt_count integer NOT NULL DEFAULT 0,
                article_correct_count integer NOT NULL DEFAULT 0,
                consecutive_serve_count integer NOT NULL DEFAULT 0,
                first_learned_date timestamp with time zone NOT NULL DEFAULT NOW(),
                last_correct_date timestamp with time zone NOT NULL DEFAULT NOW(),
                last_article_served_date timestamp with time zone NULL,
                last_article_answered_date timestamp with time zone NULL,
                CONSTRAINT fk_user_karty_learning_user
                    FOREIGN KEY (user_id) REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
                CONSTRAINT fk_user_karty_learning_karty
                    FOREIGN KEY (karty_id) REFERENCES karty(karty_id) ON DELETE CASCADE
            );

            ALTER TABLE user_karty_learning
                ADD COLUMN IF NOT EXISTS introduced_date timestamp with time zone NULL;

            -- Geriye dönük doldurma: mevcut satırların hepsi en az bir kez
            -- doğru cevaplanarak oluşmuştu, yani kullanıcı o kelimeleri zaten
            -- görmüş. Doldurulmazsa bildikleri kelimelerle yeniden
            -- tanıştırılırlardı.
            UPDATE user_karty_learning
            SET introduced_date = first_learned_date
            WHERE introduced_date IS NULL;

            ALTER TABLE user_karty_learning
                ADD COLUMN IF NOT EXISTS box integer NOT NULL DEFAULT 0;
            ALTER TABLE user_karty_learning
                ADD COLUMN IF NOT EXISTS due_date timestamp with time zone NULL;

            -- Geriye dönük doldurma. Mevcut satırların geçmişi var ama kutusu
            -- yok; hepsine kutu 1 verilseydi **hepsinin vadesi yarın** olur ve
            -- kullanıcı ertesi gün yüzlerce tekrarla karşılaşırdı.
            --
            -- Bunun yerine kutu doğru sayısından türetiliyor ve vade son
            -- doğru cevabın üstüne biniyor: son doğru tarihleri zaten
            -- birbirinden farklı olduğu için tekrarlar günlere kendiliğinden
            -- dağılıyor.
            UPDATE user_karty_learning
            SET box = LEAST(GREATEST(correct_count, 1), 5)
            WHERE box = 0 AND correct_count > 0;

            UPDATE user_karty_learning
            SET due_date = last_correct_date + (
                    CASE box
                        WHEN 1 THEN INTERVAL '1 day'
                        WHEN 2 THEN INTERVAL '3 days'
                        WHEN 3 THEN INTERVAL '7 days'
                        WHEN 4 THEN INTERVAL '14 days'
                        WHEN 5 THEN INTERVAL '30 days'
                        ELSE INTERVAL '0 days'
                    END)
            WHERE due_date IS NULL AND box > 0;

            CREATE INDEX IF NOT EXISTS ix_user_karty_learning_due
                ON user_karty_learning (user_id, due_date);

            CREATE UNIQUE INDEX IF NOT EXISTS ix_user_karty_learning_user_id_karty_id
                ON user_karty_learning (user_id, karty_id);

            CREATE INDEX IF NOT EXISTS ix_user_karty_learning_karty_id
                ON user_karty_learning (karty_id);

            CREATE INDEX IF NOT EXISTS ix_user_karty_learning_last_article_served
                ON user_karty_learning (user_id, last_article_served_date DESC);
            """,
                cancellationToken);
            _isReady = true;
        }
        finally
        {
            SchemaLock.Release();
        }
    }
}
