using Microsoft.EntityFrameworkCore;
using Postgres;

namespace Service.Helpers;

public static class UserQuestClaimSchemaHelper
{
    private static readonly SemaphoreSlim SchemaLock = new(1, 1);
    private static bool _isReady;

    public static async Task EnsureCreatedAsync(
        LingualLoopContext context,
        CancellationToken cancellationToken)
    {
        if (_isReady) return;

        await SchemaLock.WaitAsync(cancellationToken);
        try
        {
            if (_isReady) return;

            await context.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS user_quest_claim (
                    user_quest_claim_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id text NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
                    quest_key text NOT NULL,
                    day_key integer NOT NULL,
                    claimed_at timestamp with time zone NOT NULL
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ix_user_quest_claim_user_quest_day
                    ON user_quest_claim (user_id, quest_key, day_key);
                """,
                cancellationToken);

            _isReady = true;
        }
        finally
        {
            SchemaLock.Release();
        }
    }
}
