using Microsoft.EntityFrameworkCore;
using Postgres;

namespace Service.Helpers;

public static class UserDailyActivitySchemaHelper
{
    public static async Task EnsureCreatedAsync(
        LingualLoopContext context,
        CancellationToken cancellationToken)
    {
        await context.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS user_daily_activity (
                user_daily_activity_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id text NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
                activity_date date NOT NULL,
                created_at timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await context.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS ix_user_daily_activity_user_id_activity_date
            ON user_daily_activity (user_id, activity_date);
            """,
            cancellationToken);

        await context.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS user_streak (
                user_streak_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id text NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
                current_streak integer NOT NULL,
                longest_streak integer NOT NULL,
                last_active_date date NOT NULL,
                updated_at timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await context.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS ix_user_streak_user_id
            ON user_streak (user_id);
            """,
            cancellationToken);

        // Korunan gün, tahmin edilmek yerine kaydedilir.
        await context.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE user_daily_activity
                ADD COLUMN IF NOT EXISTS frozen boolean NOT NULL DEFAULT false;
            """,
            cancellationToken);

        // Oynanan gün: seri artık girişe değil gerçek etkinliğe bağlı.
        //
        // Kolon bilerek `DEFAULT true` ile ekleniyor — bu, eklendiği anda
        // tabloda bulunan **mevcut satırların tamamını "oynanmış" sayar**
        // (kullanıcı onayıyla yapılan geriye dönük doldurma). Yeni kuralı
        // geçmişe uygulamak kimsenin serisini sebepsiz kırmasın diye. Ayrı bir
        // toplu UPDATE yerine kolonun varsayılanı kullanılıyor: tek işlem ve
        // `IF NOT EXISTS` sayesinde yalnızca bir kez.
        await context.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE user_daily_activity
                ADD COLUMN IF NOT EXISTS played boolean NOT NULL DEFAULT true;
            """,
            cancellationToken);

        // Varsayılan hemen `false`'a çevriliyor: bundan sonra oluşan satırlar
        // "girildi ama henüz oynanmadı" durumunda doğmalı.
        await context.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE user_daily_activity
                ALTER COLUMN played SET DEFAULT false;
            """,
            cancellationToken);

        // Seri koruma: gün kaçırıldığında seriyi ayakta tutan sayaç.
        await context.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE user_streak
                ADD COLUMN IF NOT EXISTS freeze_count integer NOT NULL DEFAULT 0,
                ADD COLUMN IF NOT EXISTS freeze_refilled_at date;
            """,
            cancellationToken);

        // Premium üyelik. Koruma yalnızca premium üyeye verildiği için seri
        // akışının bu tabloyu okuması gerekiyor.
        await context.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS user_premium (
                user_premium_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id text NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
                premium_until timestamp with time zone,
                updated_at timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await context.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS ix_user_premium_user_id
            ON user_premium (user_id);
            """,
            cancellationToken);
    }
}
