using Microsoft.EntityFrameworkCore;
using Postgres;

namespace Service.Helpers;

public static class UserKartyHistorySchemaHelper
{
    public static Task EnsureCreatedAsync(
        LingualLoopContext context,
        CancellationToken cancellationToken)
    {
        return context.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS user_karty_history
            (
                user_karty_history_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id text NOT NULL,
                karty_id integer NOT NULL,
                wrong_count integer NOT NULL DEFAULT 0,
                last_wrong_date timestamp with time zone NOT NULL DEFAULT NOW(),
                reviewed_date timestamp with time zone NULL,
                CONSTRAINT fk_user_karty_history_user
                    FOREIGN KEY (user_id) REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
                CONSTRAINT fk_user_karty_history_karty
                    FOREIGN KEY (karty_id) REFERENCES karty(karty_id) ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ix_user_karty_history_user_id_karty_id
                ON user_karty_history (user_id, karty_id);

            CREATE INDEX IF NOT EXISTS ix_user_karty_history_karty_id
                ON user_karty_history (karty_id);

            ALTER TABLE user_karty_history
                ADD COLUMN IF NOT EXISTS wrong_count integer NOT NULL DEFAULT 0;

            ALTER TABLE user_karty_history
                ADD COLUMN IF NOT EXISTS last_wrong_date timestamp with time zone NOT NULL DEFAULT NOW();

            ALTER TABLE user_karty_history
                ADD COLUMN IF NOT EXISTS reviewed_date timestamp with time zone NULL;

            ALTER TABLE user_karty_history
                ADD COLUMN IF NOT EXISTS is_correct_answer boolean NOT NULL DEFAULT false;

            ALTER TABLE user_karty_history
                ALTER COLUMN is_correct_answer SET DEFAULT false;

            UPDATE user_karty_history
            SET last_wrong_date = NOW()
            WHERE last_wrong_date IS NULL;

            UPDATE user_karty_history
            SET is_correct_answer = false
            WHERE is_correct_answer IS NULL;
            """,
            cancellationToken);
    }
}
