using Microsoft.EntityFrameworkCore;
using Postgres;

namespace Service.Helpers;

public static class UserLeagueProgressSchemaHelper
{
    private static readonly SemaphoreSlim SchemaLock = new(1, 1);
    private static bool _isReady;

    public static async Task EnsureCreatedAsync(
        LingualLoopContext context,
        CancellationToken cancellationToken)
    {
        if (_isReady) return;

        await SchemaLock.WaitAsync(cancellationToken);
        try
        {
            if (_isReady) return;

            await context.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS user_league_progress (
                    user_league_progress_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id text NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
                    season_key integer NOT NULL,
                    points integer NOT NULL DEFAULT 0,
                    announced_league_rank integer,
                    updated_at timestamp with time zone NOT NULL
                );

                ALTER TABLE user_league_progress
                    ADD COLUMN IF NOT EXISTS announced_league_rank integer;

                -- Var olan kullanıcılar geçmişte kazandıkları ligler için
                -- toplu popup görmemeli. Sadece ilk şema yükseltmesinde null
                -- olan satırlar mevcut puan seviyesine taşınır.
                UPDATE user_league_progress
                SET announced_league_rank = CASE
                    WHEN points >= 120 THEN 11
                    WHEN points >= 90 THEN 10
                    WHEN points >= 80 THEN 9
                    WHEN points >= 70 THEN 8
                    WHEN points >= 60 THEN 7
                    WHEN points >= 50 THEN 6
                    WHEN points >= 40 THEN 5
                    WHEN points >= 30 THEN 4
                    WHEN points >= 20 THEN 3
                    WHEN points >= 10 THEN 2
                    ELSE 1
                END
                WHERE announced_league_rank IS NULL;

                ALTER TABLE user_league_progress
                    ALTER COLUMN announced_league_rank SET DEFAULT 1,
                    ALTER COLUMN announced_league_rank SET NOT NULL;

                CREATE UNIQUE INDEX IF NOT EXISTS ix_user_league_progress_user_id_season_key
                    ON user_league_progress (user_id, season_key);

                CREATE INDEX IF NOT EXISTS ix_user_league_progress_season_key_points
                    ON user_league_progress (season_key, points DESC);
                """,
                cancellationToken);

            _isReady = true;
        }
        finally
        {
            SchemaLock.Release();
        }
    }
}
